[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true
style_success = "green"
style_failure = "red"

[cmd_duration]
style = "yellow"

[directory]
style = "cyan"

[dotnet]
style = "blue"

[git_branch]
style = "purple"

[git_state]
style = "yellow"

[git_status]
style = "red"

[hostname]
ssh_only = false
style = "green"

[nodejs]
style = "green"

[package]
style = "red"

[time]
disabled = false
format = "%Y-%m-%d %T"
style = "yellow"

[username]
show_always = true
style_user = "yellow"

[python]
pyenv_version_name = true

